name: Terraform Prod Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-prod-deploy
  cancel-in-progress: false

jobs:
  deploy-prod:
    name: Plan and Apply (prod)
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: terraform/environments/prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_PROD }}
          aws-region: us-east-1

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -input=false -var-file="prod.tfvars" -out="prod.tfplan"

      - name: Terraform apply
        run: terraform apply -input=false -auto-approve "prod.tfplan"
